# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e8fe13b767fde3ac337538aa8838763520bd0ab3622063e34828585241a82f8075f2fec08c38c164f6568876ce655342878eb895ac7572172050b398d9495e0

test:
  secret_key_base: 45480d74c24b39e9ade578f5889d98703460572bd21a49a1eeda08cd034d808c29d7cb374b5811d29c6455a70a6860e2e30bc1b0e57cf1213c44abd462ad2c13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
